Geolocation
Stratio/hermes pull request #11
Opened 2016-12-09 12:20 UTC by eruizgar

## Description

- This feature extends Hermes with the porpouse of generate random geolocations. 
- The complete description of how use methods is in README.md included.

### Testing
- You could find unit test in HermesTest.scala
- [X] Unit, integration, acceptance tests as appropriate
- [X] Coverage (>90%)

### Documentation
- [ ] Changelog update
- [X] Documentation entry

### Scalastyle
Result of scalastyle execution:

2016-12-09 12:26 UTC, anistal reviewed
All OK. You have forgotten to delete lines in US locale (that has tons of lines)

2016-12-09 12:26 UTC, anistal commented on src/main/resources/locales/geo/US.json
> +[{"latitude": 39.6335556, "longitude": -86.8138056},
Only 50 entries please

2016-12-09 12:53 UTC, albertostratio requested changes
@eruizgar I missed tests cases for some of our acceptance criteria: the ones where some records of our files have records corrupted, could you please add tests for these cases?

2016-12-09 12:53 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/utils/HermesTest.scala
> +    hermesES.Geo.geoModel should contain (hermesES.Geo geolocation)
It doesn't matter but to be consistent with the next check I'd add a period after the Geo -> (hermesEs.Geo.geolocation)

2016-12-09 12:53 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/utils/HermesTest.scala
> +  it should "raise an exception when it gets a geolocation are empty in the locale" in {
The test descripcion is not clear I'd change it to be: it should "raise a NoSuchElementException when the locale is empty"

2016-12-13 08:35 UTC, albertostratio requested changes

2016-12-13 08:35 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/utils/HermesTest.scala
>    /**
With the changes that you've just made I guess we should include more tests to fulfill the acceptance criteria.

2016-12-13 08:35 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/utils/Hermes.scala
> +    def geolocationOfGeoModel(l: List[Either[String, Seq[GeoModel]]]): List[GeoModel] = {
I would call this method: geoModelList

2016-12-13 11:09 UTC, albertostratio approved these changes

2016-12-13 11:10 UTC, albertostratio commented
Coverage = 95%, good joob @eruizgar !!

LGTM

2016-12-13 11:16 UTC, merged