[DCS-532] Produce messages to kafka using Stratio Hermes
Stratio/hermes pull request #15
Opened 2016-12-14 14:13 UTC by anistal

## Description
Now, when Hermes starts it produces messages in a Kafka's broker.

### Testing
You should start n instances of Hermes and check that it is producing messages in a Kafka's broker.

- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Coverage (>90%)

### Documentation
- [ ] Changelog update
- [ ] Documentation entry

### Scalastyle
Result of scalastyle execution: All OK.

2016-12-14 14:33 UTC, aalfonso-stratio reviewed
Add info to changelog, please

2016-12-14 14:37 UTC, aalfonso-stratio reviewed
Please, update documentation to note this new functionality and how to use it

2016-12-14 14:56 UTC, aalfonso-stratio reviewed
docker-entrypoint.sh needs to be modified to cope with the new elements in application.conf

2016-12-14 16:56 UTC, eruizgar requested changes

2016-12-14 16:56 UTC, eruizgar commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +  propsProducer.put("key.serializer" , "org.apache.kafka.common.serialization.StringSerializer")
Can we add that property to application.conf?

2016-12-14 16:56 UTC, eruizgar commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +  propsProducer.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer")
Same comment as above

2016-12-14 16:56 UTC, eruizgar commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +  propsProducer.put("request.requieres.acks", "1")
Same comment as above

2016-12-14 16:56 UTC, eruizgar commented on src/test/scala/com/stratio/hermes/actors/HermesActorTest.scala
> +//  lazy implicit val config: Config = ConfigFactory.parseString(HermesActorTest.DefaultConfig)
Remove that comment

2016-12-14 20:16 UTC, albertostratio requested changes

2016-12-14 20:16 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +      (1 to Runtime.getRuntime.availableProcessors).foreach(startThread(_, count, initialTime))
Would be a good idea to pick half of the available processors instead of all of them?

2016-12-14 20:16 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +        val hermes = Hermes()
This does not take into account the locale, isn't? Is just a first approach? Have you thought how to add the locale when instantiating the hermes generator?

2016-12-14 20:16 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/helpers/HermesRunnerHelper.scala
> +    system.scheduler.scheduleOnce(5 seconds) {
Does it make sense to add the 5 value as a config variable?

2016-12-14 20:16 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/helpers/HermesRunnerHelperTest.scala
> +    "print a welcome message and start the akka system without errors" in {
This test checks nothing, isn't?

2016-12-14 20:16 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/helpers/HermesRunnerHelperTest.scala
> +      HermesRunnerHelper.workerSupervisor
This test checks nothing, isn't?

2016-12-14 20:16 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/runners/HermesRunnerTest.scala
> +      HermesRunner.main(Array.empty)
This test checks nothing at all, isn't?

2016-12-15 08:27 UTC, anistal commented on src/test/scala/com/stratio/hermes/helpers/HermesRunnerHelperTest.scala
> +    "print a welcome message and start the akka system without errors" in {
It test that implicits values are setted previusly and execute lines that increase the coverage. In my opinion it does not hurt.

2016-12-15 08:32 UTC, anistal commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +        val hermes = Hermes()
Effectively it is the first approach. When a json schema configuration will be defined then it could configure how events are generated.

2016-12-15 09:22 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +        val hermes = Hermes()
Ok, fair enough!

2016-12-15 10:39 UTC, anistal commented on src/test/scala/com/stratio/hermes/helpers/HermesRunnerHelperTest.scala
> +      HermesRunnerHelper.workerSupervisor
same of above

2016-12-15 10:39 UTC, anistal commented on src/test/scala/com/stratio/hermes/runners/HermesRunnerTest.scala
> +      HermesRunner.main(Array.empty)
same of above

2016-12-19 10:17 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/actors/HermesActorTest.scala
> +
Could you please get rid of this blank line?

2016-12-19 10:24 UTC, albertostratio requested changes

2016-12-19 10:24 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/actors/HermesActorTest.scala
> +
Could you please get rid of this blank line?

2016-12-19 10:24 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/kafka/KafkaClientIT.scala
> +    AdminUtils.createTopic(zkUtils, topicName, Partitions, ReplicationFactor, new Properties())
How does it behave when the topic already exist? I mean, if we execute this test several times the topic might exist already...have you tested this scenario? Would it be useful to include an afterAll step to delete the topic??

2016-12-19 10:31 UTC, anistal commented on src/test/scala/com/stratio/hermes/kafka/KafkaClientIT.scala
> +    AdminUtils.createTopic(zkUtils, topicName, Partitions, ReplicationFactor, new Properties())
The topic will be always different: val Topic = s"topic-${UUID.randomUUID().toString}"

2016-12-19 10:36 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/kafka/KafkaClientIT.scala
> +    AdminUtils.createTopic(zkUtils, topicName, Partitions, ReplicationFactor, new Properties())
ok, fair enough. Thank you @anistal

2016-12-19 10:38 UTC, albertostratio approved these changes

2016-12-19 10:41 UTC, eruizgar approved these changes

2016-12-19 10:48 UTC, merged