Feature/hermes start message
Stratio/hermes pull request #28
Opened 2017-01-16 11:34 UTC by anistal

## Description

Start producing messages in a dynamic way

### Testing
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Coverage (>90%)

### Documentation
- [ ] Changelog update
- [ ] Documentation entry

### Scalastyle
Result of scalastyle execution:

2017-01-18 10:01 UTC, albertostratio requested changes

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/actors/HermesSupervisorActor.scala
> +
Could you please get rid of this blank line?

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/actors/HermesSupervisorActor.scala
> +    case HermesExecutorActor.Start(hc) =>
I'd modify the name of hc to be something clearer like config or hermesConfig

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/actors/HermesSupervisorActor.scala
> +        parserOption match {
Would it make sense to replace this pattern matching for a more-idiomatic way use of Option (using map & getOrElse)? For further details have a look at this post: [Your options do not match](http://blog.originate.com/blog/2014/06/15/idiomatic-scala-your-options-do-not-match/)

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/constants/HermesConstants.scala
could you please get rid of this blank line?

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/constants/HermesConstants.scala
could you please get rid of this blank line?

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/helpers/HermesConfig.scala
> +    if(kafkaConfig.getString("kafka.key.serializer") == "io.confluent.kafka.serializers.KafkaAvroSerializer") {
Would it make sense to extract the string "io.confluent.kafka.serializers.KafkaAvroSerializer" to a val or even a config value?

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/helpers/HermesRunnerHelper.scala
> +      |  topic = "chustas"
chustas? :)

2017-01-18 10:01 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/helpers/HermesRunnerHelper.scala
> +      |  template-name = "chustasTemplate"
chustasTemplate? :)

2017-01-18 10:01 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +      }
I missed the following tests (not sure whether they're feasible to implement though):
- Start an already started worker to test the assertStopped method
- Test the isAMessageForMe method by passing-in a non empty sequence of non existing ids

2017-02-21 07:33 UTC, anistal commented on src/test/scala/com/stratio/hermes/actors/WorkerSupervisorActor.scala
> +      }
It makes sense, but it will be implemented in the next iteration of the project if you don't care.

2017-02-22 08:24 UTC, albertostratio approved these changes
LGTM

2017-02-22 08:24 UTC, merged