Generate from range
Stratio/hermes pull request #30
Opened 2017-02-22 09:46 UTC by eruizgar

## Description
Now you can create number or decimal included in a range of two numbers.

### Testing
- [X] Unit, integration, acceptance tests as appropriate
- [ ] Coverage (>90%)

### Documentation
- [X] Changelog update
- [X] Documentation entry

### Scalastyle
Result of scalastyle execution: 
Processed 26 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 1941 ms

2017-02-22 14:04 UTC, albertostratio requested changes

2017-02-22 14:04 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/utils/HermesTest.scala
> +    numberOfDigitsFromANumber(hermesNum.Number.numberInRange(99,10)) shouldBe 2
It shouldn't be numberInRange(10,99)??

2017-02-22 14:27 UTC, eruizgar commented on src/test/scala/com/stratio/hermes/utils/HermesTest.scala
> +    numberOfDigitsFromANumber(hermesNum.Number.numberInRange(99,10)) shouldBe 2
You can pass the range in both ways, (10,99) and (99,10)

2017-02-23 07:01 UTC, albertostratio commented on src/test/scala/com/stratio/hermes/utils/HermesTest.scala
> +    numberOfDigitsFromANumber(hermesNum.Number.numberInRange(99,10)) shouldBe 2
ok, fair enough

2017-02-23 07:02 UTC, albertostratio approved these changes
LGTM

2017-03-01 10:14 UTC, merged