[Khermes #42]Rename project to Khermes
Stratio/hermes pull request #56
Opened 2017-03-13 18:18 UTC by eruizgar

## Description

Add a description of your changes here.

### Testing
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Coverage (>90%)

### Documentation
- [ ] Changelog update
- [ ] Documentation entry

### Scalastyle
Result of scalastyle execution:

2017-03-13 19:13 UTC, albertostratio requested changes
@eruizgar having a quick look I noticed that you have renamed the classes using capitals for the two first letters (KHermesClientActor, KHermesConfig, KHermesRunnerHelper...) this could be error prone and does not follow the scala name convention. Would you mind changing the name of the classes?

2017-03-14 06:59 UTC, albertostratio approved these changes

2017-03-14 07:00 UTC, albertostratio commented
Thank you very much @eruizgar ! Build is failing though :(

2017-03-14 07:09 UTC, anistal commented
You forgot to rename the logo in the shell with Hermes to Khermes.

2017-03-14 08:30 UTC, merged