Feature/hermes clustering
Stratio/hermes pull request #7
Opened 2016-11-30 19:52 UTC by anistal

## Description
Definition of an skeleton that allows  to run Hermes using Akka Clustering. 

### Testing
You should test these scenarios:
1. With the purpose of to simulate an Akka Cluster a new test was added: ClusterHermesMultiJvmSpec.scala. This is a special test because it should be run using sbt.
You should follow these steps:
   * Run sbt from the shell:
     ```shell
     $ ~/hermes/sbt
     ```
   * Pass this special test with this command:
     ```shell
     [info] Loading project definition from /home/anistal/Projects/genesis/project
     [info] Set current project to hermes (in build file:/~/hermes/)
     > multi-jvm:test
     ```
2. Manual testing running Hermes with three nodes. Steps:
   * Package generation.
     ```shell
     $ mvn clean package
     ```
   * Run a seed node (by default in the port 2551).
     ```shell
     java -Dakka.remote.netty.tcp.port=2551 -jar ~/hermes/target/hermes-0.1.0-SNAPSHOT-allinone.jar   
     ```
   * Run another two nodes (that will be use the first node as the seed).
     ```shell
     java -Dakka.remote.netty.tcp.port=2552 -jar ~/hermes/target/hermes-0.1.0-SNAPSHOT-allinone.jar
     ```
     ```shell
     java -Dakka.remote.netty.tcp.port=2552 -jar ~/hermes/target/hermes-0.1.0-SNAPSHOT-allinone.jar
     ```
Important note: due to the difficulty of test an akka cluster and that the "special" test is not included in the coverage, it could be less than before.

- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Coverage (>90%)

### Documentation
- [ ] Changelog update
- [ ] Documentation entry

### Scalastyle
Result of scalastyle execution: No warnings or errors.

2016-12-01 11:46 UTC, albertostratio requested changes
Some minor changes. Good job!!

2016-12-01 11:46 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/runners/HermesRunner.scala
> +
Could you please get rid of these blank lines?

2016-12-01 11:46 UTC, albertostratio commented on src/multi-jvm/scala/com/stratio/hermes/multinode/ClusterHermesMultiJvmSpec.scala
> +
Could you please put together all the vals of the class?

2016-12-01 11:46 UTC, albertostratio commented on src/main/scala/com/stratio/hermes/runners/HermesRunner.scala
> +
Could you please get rid of these blank lines?

2016-12-02 11:54 UTC, adoblas approved these changes
LGTM

2016-12-02 11:57 UTC, albertostratio approved these changes

2016-12-02 11:59 UTC, merged