[Khermes #48]Multiple configs
Stratio/hermes pull request #74
Opened 2017-03-20 00:13 UTC by eruizgar

## Description
- Now you can save different configurations in zookeeper.
- You can show your configurations.
Example:
show --kafka k1
start -t t1 -k k1 -h h1 --ids 92138793

### Testing
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Coverage (>90%)

### Documentation
- [ ] Changelog update
- [ ] Documentation entry

### Scalastyle
Result of scalastyle execution:

2017-03-20 19:18 UTC, albertostratio requested changes

2017-03-20 19:18 UTC, albertostratio commented on README.md
> +Khermes client provide the next commands to manage your Khermes cluster:
Khermes client provides...

2017-03-20 19:18 UTC, albertostratio commented on README.md
> +       -h, --khermes    : Khermes configuration
After changing the name to khermes is a bit weird to set the khermes config with an h, should we use kh for khermes config and ka for kafka??

2017-03-20 19:18 UTC, albertostratio commented on README.md
> +       -h, --khermes    : Khermes configuration
Same comment as above

2017-03-20 19:18 UTC, albertostratio commented on README.md
> +       -h, --khermes    : Khermes configuration
Same comment as above

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/ArgsParser.scala
> +  }
I'd add a blank line after this

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/ArgsParser.scala
> +  def commandWord(line: String):String={
Be careful with spaces after "=" and before "{"

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/ArgsParser.scala
> +  def parse(line: String): Map[String, List[String]] ={
I'd change the name of the method to better explain what's doing, this method has 5 lines and is doing too much to named it just parse

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/KhermesConsoleHelper.scala
> +    s"""Khermes client provide the next commands to manage your Khermes cluster:
Khermes client provides...

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/KhermesConsoleHelper.scala
> +       |       -h, --khermes    : Khermes configuration
Same comment as above regarding -h

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/KhermesConsoleHelper.scala
> +       |       -h, --khermes    : Khermes configuration
Same comment as above regarding -h

2017-03-20 19:18 UTC, albertostratio commented on src/main/scala/com/stratio/khermes/helpers/KhermesConsoleHelper.scala
> +       |       -h, --khermes    : Khermes configuration
Same comment as above regarding -h

2017-03-20 19:18 UTC, albertostratio commented on src/test/scala/com/stratio/khermes/helpers/ArgsParserTest.scala
> +    }
I missed some tests for sad path, the method parser within the ArgsParser class has 5 lines, not sure whether you're testing all the paths with just this test

2017-03-20 19:18 UTC, albertostratio commented on src/test/scala/com/stratio/khermes/helpers/KhermesConsoleHelperTest.scala
> +class KhermesConsoleHelperTest extends FlatSpec
It seems like this test is failing in travis.ci, could you please have a look: [travis-build-error](https://travis-ci.org/Stratio/khermes/builds/212828061)

2017-03-20 19:18 UTC, albertostratio commented on src/test/scala/com/stratio/khermes/helpers/KhermesConsoleHelperTest.scala
> +//    khermesConsoleHelper.save(Map("fail" -> List("a1")),"save",None) shouldBe "Arg fail is not correct."
Could you please get rid of this comment?

2017-03-21 10:53 UTC, eruizgar commented on src/test/scala/com/stratio/khermes/helpers/KhermesConsoleHelperTest.scala
> +class KhermesConsoleHelperTest extends FlatSpec
With the refactor that @anistal is planning that test will not make sense. I have commmented until we decide how continue, if we use a websocket client...

2017-03-22 07:43 UTC, albertostratio approved these changes
LGTM

2017-04-14 19:01 UTC, closed without merging